name: Wrangler

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-deploy-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Configure Wrangler CLI
        run: |
          mkdir -p ~/.wrangler/config
          echo "api_token = \"${{ secrets.CLOUDFLARE_API_KEY }}\"" > ~/.wrangler/config/default.toml

      - name: Inject settings for the project
        run: |
          cp ./wrangler.example.toml ./wrangler.toml
          sed -i 's/{{ACCOUNT_ID}}/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/' ./wrangler.toml
          sed -i 's/{{PUBLIC_KEY}}/${{ secrets.DISCORD_PUBLIC_KEY }}/' ./wrangler.toml

      - name: Deploy to Cloudflare Workers
        run: wrangler publish
